name: main

on:
  schedule:
    - cron: "1 0 * * *"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3, actions/setup-node@v3
      - name: install-chromium
        run: |
          sudo apt-get install chromium-browser
          export CHROME_BIN=/usr/bin/chromium-browser
      
      - name: run-files
        with:
          node-version: "18"
        run: |
          node node/scrape.js
          node node/horizons.js

      - name: push-job
        run: |
          git config --global user.name 'HarisVidimlic19'
          git config --global user.email 'hvidimlic1234@hotmail.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git checkout "${GITHUB_REF:11}"
          git add -A
          git commit -am "Automated data import"
          git push origin main