name: run-node-files-and-push

on:
  schedule:
    - cron: '1 0 * * *'

jobs:
  run-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      - run: node scrape.js
        working-directory: ./node
      - run: node horizons.js
        working-directory: ./node
  push-job:
    needs: run-files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Push changes
        run: git push origin main
